# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='topic',
            new_name='category',
        ),
    ]
